development: &development
  adapter: postgresql
  encoding: unicode
  host: 'localhost'
  database: 'library_dev'
  username: 
  password: 
  pool: 5

test: &test
  <<: *development
  database: 'library_test'
  username: 
  password: 
  pool: 5
